# Generated by Django 5.0.1 on 2024-02-05 19:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgeRestriction',
            fields=[
                ('id', models.SmallIntegerField(primary_key=True, serialize=False, unique=True)),
                ('label', models.CharField(max_length=8, unique=True)),
            ],
            options={
                'verbose_name': 'Возрастное ограничение',
                'verbose_name_plural': 'Возрастное ограничение',
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.SmallIntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=64, unique=True)),
            ],
            options={
                'verbose_name': 'Жанр',
                'verbose_name_plural': 'Жанр',
            },
        ),
        migrations.CreateModel(
            name='MangaStatus',
            fields=[
                ('id', models.SmallIntegerField(primary_key=True, serialize=False, unique=True)),
                ('label', models.CharField(max_length=32, unique=True)),
            ],
            options={
                'verbose_name': 'Статус выпуска манги',
                'verbose_name_plural': 'Статус выпуска манги',
            },
        ),
        migrations.CreateModel(
            name='MangaType',
            fields=[
                ('id', models.SmallIntegerField(primary_key=True, serialize=False, unique=True)),
                ('label', models.CharField(max_length=32, unique=True)),
            ],
            options={
                'verbose_name': 'Тип произведения',
                'verbose_name_plural': 'Тип произведения',
            },
        ),
        migrations.CreateModel(
            name='Moderated',
            fields=[
                ('id', models.SmallIntegerField(primary_key=True, serialize=False, unique=True)),
                ('label', models.CharField(max_length=32, unique=True)),
            ],
            options={
                'verbose_name': 'Статус модерации',
                'verbose_name_plural': 'Статус модерации',
            },
        ),
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.SmallIntegerField(primary_key=True, serialize=False, unique=True)),
                ('slug', models.CharField(max_length=255, unique=True)),
                ('slug_url', models.CharField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('rus_name', models.CharField(max_length=255, null=True, unique=True)),
                ('alt_name', models.CharField(max_length=255, null=True, unique=True)),
                ('cover', models.JSONField(null=True)),
                ('subscription', models.JSONField(null=True)),
                ('user_id', models.SmallIntegerField()),
                ('titles_count_details', models.CharField(max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Автор',
                'verbose_name_plural': 'Автор',
            },
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.SmallIntegerField(primary_key=True, serialize=False, unique=True)),
                ('slug', models.CharField(max_length=255, unique=True)),
                ('slug_url', models.CharField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('rus_name', models.CharField(max_length=255, null=True, unique=True)),
                ('cover', models.JSONField(null=True)),
                ('subscription', models.JSONField(null=True)),
            ],
            options={
                'verbose_name': 'Издатель',
                'verbose_name_plural': 'Издатель',
            },
        ),
        migrations.CreateModel(
            name='ScanlateStatus',
            fields=[
                ('id', models.SmallIntegerField(primary_key=True, serialize=False, unique=True)),
                ('label', models.CharField(max_length=32, unique=True)),
            ],
            options={
                'verbose_name': 'Статус выпуска перевода',
                'verbose_name_plural': 'Статус выпуска перевода',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.SmallIntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=64, unique=True)),
            ],
            options={
                'verbose_name': 'Тег',
                'verbose_name_plural': 'Тег',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.SmallIntegerField(primary_key=True, serialize=False, unique=True)),
                ('slug', models.CharField(max_length=255, unique=True)),
                ('slug_url', models.CharField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('cover', models.JSONField()),
                ('details', models.JSONField()),
            ],
            options={
                'verbose_name': 'Переводчики',
                'verbose_name_plural': 'Переводчики',
            },
        ),
        migrations.CreateModel(
            name='Manga',
            fields=[
                ('id', models.SmallIntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('rus_name', models.CharField(max_length=255)),
                ('eng_name', models.CharField(max_length=255)),
                ('otherNames', models.JSONField()),
                ('slug', models.CharField(max_length=255)),
                ('slug_url', models.CharField(max_length=255)),
                ('cover', models.JSONField()),
                ('background', models.JSONField()),
                ('site', models.SmallIntegerField()),
                ('summary', models.TextField()),
                ('close_view', models.SmallIntegerField()),
                ('releaseDate', models.SmallIntegerField()),
                ('views', models.JSONField()),
                ('rating', models.JSONField()),
                ('is_licensed', models.BooleanField()),
                ('metadata', models.JSONField()),
                ('model', models.CharField(max_length=255)),
                ('items_count', models.JSONField()),
                ('format', models.JSONField()),
                ('release_date_string', models.CharField(max_length=16)),
                ('age_restriction', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='manga.agerestriction')),
                ('genres', models.ManyToManyField(to='manga.genre')),
                ('status', models.ManyToManyField(to='manga.mangastatus')),
                ('type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='manga.mangatype')),
                ('moderated', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='manga.moderated')),
                ('artists', models.ManyToManyField(related_name='artist_manga_set', to='manga.people')),
                ('authors', models.ManyToManyField(related_name='author_manga_set', to='manga.people')),
                ('publisher', models.ManyToManyField(to='manga.publisher')),
                ('scanlate_status', models.ManyToManyField(to='manga.scanlatestatus')),
                ('tags', models.ManyToManyField(to='manga.tag')),
                ('teams', models.ManyToManyField(to='manga.team')),
            ],
            options={
                'verbose_name': 'Манга',
                'verbose_name_plural': 'Манга',
            },
        ),
    ]
