# Generated by Django 5.0.1 on 2024-02-05 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('chapter_id', models.PositiveIntegerField(primary_key=True, serialize=False, unique=True)),
                ('chapter_slug', models.CharField(max_length=255, unique=True)),
                ('chapter_name', models.CharField(max_length=255)),
                ('chapter_number', models.CharField(max_length=12)),
                ('chapter_volume', models.PositiveSmallIntegerField()),
                ('chapter_moderated', models.PositiveSmallIntegerField()),
                ('chapter_user_id', models.PositiveIntegerField()),
                ('chapter_expired_at', models.CharField(max_length=20)),
                ('chapter_created_at', models.CharField(max_length=20)),
                ('chapter_scanlator_id', models.PositiveSmallIntegerField()),
                ('status', models.CharField(max_length=255, null=True)),
                ('price', models.PositiveIntegerField()),
                ('branch_id', models.PositiveIntegerField()),
                ('username', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Глава',
                'verbose_name_plural': 'Глава',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('name', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('href', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'Тег',
                'verbose_name_plural': 'Тег',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.PositiveSmallIntegerField(primary_key=True, serialize=False, unique=True)),
                ('branch_id', models.PositiveSmallIntegerField()),
                ('href', models.CharField(max_length=255, unique=True)),
                ('img', models.CharField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('alt_name', models.CharField(max_length=255, unique=True)),
                ('cover', models.CharField(max_length=32)),
                ('slug', models.CharField(max_length=255, unique=True)),
                ('sale', models.PositiveSmallIntegerField()),
                ('pivot', models.JSONField()),
            ],
            options={
                'verbose_name': 'Комманда переводчиков',
                'verbose_name_plural': 'Комманда переводчиков',
            },
        ),
        migrations.CreateModel(
            name='Manga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.CharField(max_length=255, unique=True)),
                ('href', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(unique=True)),
                ('type', models.CharField(max_length=32)),
                ('release_year', models.PositiveSmallIntegerField()),
                ('title_status', models.CharField(max_length=32)),
                ('transfer_status', models.CharField(max_length=32)),
                ('author', models.CharField(max_length=255)),
                ('artist', models.CharField(max_length=255)),
                ('publishing_house', models.CharField(max_length=255)),
                ('age_rating', models.CharField(max_length=3)),
                ('chapters_uploaded', models.PositiveSmallIntegerField()),
                ('alternative_names', models.JSONField(null=True, unique=True)),
                ('rus_name', models.CharField(max_length=255, unique=True)),
                ('eng_name', models.CharField(max_length=255, unique=True)),
                ('slug', models.CharField(max_length=255, unique=True)),
                ('status', models.PositiveSmallIntegerField()),
                ('in_lists', models.JSONField(null=True)),
                ('rating', models.FloatField(null=True)),
                ('number_of_ratings', models.PositiveIntegerField(null=True)),
                ('scores', models.JSONField(null=True)),
                ('related', models.JSONField(null=True)),
                ('similar', models.JSONField(null=True)),
                ('chapters', models.ManyToManyField(to='manga.chapter')),
                ('tags', models.ManyToManyField(to='manga.tag')),
                ('teams', models.ManyToManyField(to='manga.team')),
            ],
            options={
                'verbose_name': 'Манга',
                'verbose_name_plural': 'Манга',
            },
        ),
    ]
