# Generated by Django 5.0.1 on 2024-02-06 11:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manga', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MangaUser',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False, unique=True)),
                ('username', models.CharField(max_length=255, unique=True)),
                ('avatar', models.JSONField(default=None, null=True)),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователь',
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False, unique=True)),
                ('image', models.CharField(max_length=255, null=True)),
                ('slug', models.PositiveSmallIntegerField()),
                ('external', models.PositiveSmallIntegerField()),
                ('chunks', models.PositiveSmallIntegerField()),
                ('chapter_id', models.PositiveIntegerField(unique=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('height', models.PositiveSmallIntegerField()),
                ('width', models.PositiveSmallIntegerField()),
                ('url', models.CharField(max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Страница',
                'verbose_name_plural': 'Страница',
            },
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(null=True)),
                ('type', models.CharField(max_length=32, null=True)),
                ('index', models.PositiveSmallIntegerField()),
                ('item_number', models.PositiveSmallIntegerField()),
                ('volume', models.CharField(max_length=32)),
                ('number', models.CharField(max_length=32)),
                ('number_secondary', models.CharField(max_length=32)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.CharField(max_length=255, null=True)),
                ('branches_count', models.PositiveSmallIntegerField()),
                ('manga_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manga.manga')),
                ('moderated', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='manga.moderated')),
                ('teams', models.ManyToManyField(to='manga.team')),
            ],
            options={
                'verbose_name': 'Глава',
                'verbose_name_plural': 'Глава',
            },
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False, unique=True)),
                ('branch_id', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField()),
                ('teams', models.ManyToManyField(to='manga.team')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manga.mangauser')),
            ],
            options={
                'verbose_name': 'Ветка',
                'verbose_name_plural': 'Ветка',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False, unique=True)),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField()),
                ('comment_level', models.PositiveSmallIntegerField()),
                ('votes_up', models.PositiveIntegerField()),
                ('votes_down', models.PositiveIntegerField()),
                ('relation_type', models.CharField(max_length=255)),
                ('relation_id', models.PositiveIntegerField()),
                ('parent_comment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parent_comment_foreigth_key', to='manga.comment')),
                ('root_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='root_comment_foreigth_key', to='manga.comment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manga.mangauser')),
                ('post_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manga.page')),
            ],
            options={
                'verbose_name': 'Глава',
                'verbose_name_plural': 'Глава',
            },
        ),
    ]
