# Generated by Django 5.0.1 on 2024-02-06 13:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manga', '0002_mangauser_page_chapter_branch_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='manga',
            old_name='otherNames',
            new_name='other_names',
        ),
        migrations.RenameField(
            model_name='manga',
            old_name='releaseDate',
            new_name='release_date',
        ),
        migrations.AddField(
            model_name='people',
            name='confirmed',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.RemoveField(
            model_name='manga',
            name='scanlate_status',
        ),
        migrations.RemoveField(
            model_name='manga',
            name='status',
        ),
        migrations.AddField(
            model_name='manga',
            name='scanlate_status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='manga.scanlatestatus'),
        ),
        migrations.AddField(
            model_name='manga',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='manga.mangastatus'),
        ),
    ]
