# Generated by Django 5.0.1 on 2024-02-06 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manga', '0003_rename_othernames_manga_other_names_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='manga',
            old_name='publisher',
            new_name='publishers',
        ),
    ]
