# Generated by Django 5.0.1 on 2024-02-06 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manga', '0004_rename_publisher_manga_publishers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manga',
            name='summary',
            field=models.TextField(null=True),
        ),
    ]
