# Generated by Django 5.0.1 on 2024-02-06 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manga', '0006_alter_manga_close_view_alter_manga_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='people',
            name='slug',
            field=models.CharField(max_length=255),
        ),
    ]
