# Generated by Django 5.0.1 on 2024-02-06 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manga', '0007_alter_people_name_alter_people_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='alt_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='people',
            name='rus_name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
