# Generated by Django 5.0.1 on 2024-02-06 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manga', '0008_alter_people_alt_name_alter_people_rus_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publisher',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='rus_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='slug',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='team',
            name='slug',
            field=models.CharField(max_length=255),
        ),
    ]
