# Generated by Django 5.0.1 on 2024-02-07 10:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manga', '0009_alter_publisher_name_alter_publisher_rus_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='manga_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='manga.manga'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='post_page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='manga.page'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='manga.mangauser'),
        ),
        migrations.AlterField(
            model_name='team',
            name='details',
            field=models.JSONField(null=True),
        ),
    ]
