# Generated by Django 5.0.1 on 2024-02-07 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manga', '0010_alter_chapter_manga_id_alter_comment_post_page_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='branch_id',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
