# Generated by Django 5.0.1 on 2024-02-07 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manga', '0011_alter_branch_branch_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
