# Generated by Django 5.0.1 on 2024-02-07 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manga', '0012_alter_chapter_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mangauser',
            name='username',
            field=models.CharField(max_length=255),
        ),
    ]
