# Generated by Django 5.0.1 on 2024-02-07 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manga', '0013_alter_mangauser_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='manga',
            name='parse_priority',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
