# Generated by Django 5.0.1 on 2024-02-08 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manga', '0014_manga_parse_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manga',
            name='parse_priority',
            field=models.SmallIntegerField(default=1),
        ),
    ]
