# Generated by Django 5.0.1 on 2024-02-10 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manga', '0016_chapter_likes_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='discord',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='vk',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
