# Generated by Django 5.0.1 on 2024-02-10 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manga', '0018_alter_page_chapter_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='updated_at',
            field=models.DateTimeField(null=True),
        ),
    ]
