# Generated by Django 5.0.1 on 2024-02-27 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manga', '0019_alter_page_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='ratio',
            field=models.FloatField(default=0.0),
        ),
    ]
