# Generated by Django 5.0.1 on 2024-02-27 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manga', '0020_page_ratio'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='deleted',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='updated_at',
            field=models.DateTimeField(null=True),
        ),
    ]
