# Generated by Django 5.0.1 on 2024-02-27 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manga', '0026_comment_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='relation_id',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
