# Generated by Django 5.0.1 on 2024-02-27 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manga', '0027_alter_comment_relation_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='model',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
