# Generated by Django 5.0.1 on 2024-03-01 04:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manga', '0028_team_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='post_page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='manga.page'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='manga.mangauser'),
        ),
    ]
