# Generated by Django 5.0.1 on 2024-03-15 11:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manga', '0029_alter_comment_post_page_alter_comment_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emotion',
            fields=[
                ('name', models.CharField(max_length=9, primary_key=True, serialize=False, unique=True)),
            ],
            options={
                'verbose_name': 'Эмоция',
                'verbose_name_plural': 'Эмоция',
            },
        ),
        migrations.AddField(
            model_name='comment',
            name='toxic',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='parent_comment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='root_comment_foreigth_key', to='manga.comment'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='root_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parent_comment_foreigth_key', to='manga.comment'),
        ),
        migrations.CreateModel(
            name='CommentEmotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('power', models.FloatField()),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manga.comment')),
                ('emotion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manga.emotion')),
            ],
            options={
                'verbose_name': 'Эмоция комментария',
                'verbose_name_plural': 'Эмоция комментария',
            },
        ),
        migrations.AddField(
            model_name='comment',
            name='emotion',
            field=models.ManyToManyField(through='manga.CommentEmotion', to='manga.emotion'),
        ),
    ]
