# Generated by Django 5.0.1 on 2024-03-15 12:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manga', '0030_emotion_comment_toxic_alter_comment_parent_comment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentemotion',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='emotion',
        ),
        migrations.AddField(
            model_name='comment',
            name='emotion',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='manga.commentemotion'),
        ),
    ]
