# Generated by Django 5.0.1 on 2024-03-15 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manga', '0032_remove_comment_emotion'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='emotion',
            field=models.FloatField(default=None, null=True),
        ),
    ]
