# Generated by Django 5.0.1 on 2024-03-15 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manga', '0033_comment_emotion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='emotion',
            field=models.FloatField(default=13.54, null=True),
        ),
    ]
