# Generated by Django 5.0.1 on 2024-03-15 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manga', '0040_comment_emotion'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='comment',
            name='manga_comme_emotion_d0a4b0_idx',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='emotion',
        ),
    ]
