# Generated by Django 5.0.1 on 2024-03-15 17:36

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manga', '0042_delete_commentemotion'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentEmotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('power', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('comment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='comment_emotion', to='manga.comment')),
                ('emotion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manga.emotion')),
            ],
            options={
                'verbose_name': 'Эмоция комментария',
                'verbose_name_plural': 'Эмоция комментария',
            },
        ),
    ]
