# Generated by Django 5.0.1 on 2024-03-15 17:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manga', '0043_commentemotion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentemotion',
            name='id',
        ),
        migrations.AlterField(
            model_name='commentemotion',
            name='comment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='comment_emotion', serialize=False, to='manga.comment'),
        ),
    ]
