# Generated by Django 5.0.1 on 2024-03-15 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manga', '0044_remove_commentemotion_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emotion',
            name='name',
            field=models.CharField(max_length=12, primary_key=True, serialize=False, unique=True),
        ),
    ]
