# Generated by Django 5.0.3 on 2024-03-23 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manga', '0045_alter_emotion_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': 'Комметарий', 'verbose_name_plural': 'Комметарий'},
        ),
        migrations.RemoveField(
            model_name='manga',
            name='parse_priority',
        ),
    ]
