# Generated by Django 5.0.3 on 2024-03-30 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manga', '0047_stats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stats',
            name='bookmarks',
            field=models.JSONField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='stats',
            name='rating',
            field=models.JSONField(default=None, null=True),
        ),
    ]
