# Generated by Django 5.0.3 on 2024-03-30 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manga', '0048_alter_stats_bookmarks_alter_stats_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='stats',
            name='last_update',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
