# Generated by Django 5.0.3 on 2024-04-05 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manga', '0049_stats_last_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='toxic',
            field=models.FloatField(db_index=True, default=None, null=True),
        ),
    ]
