# Generated by Django 5.0.1 on 2024-03-20 11:02

import annoying.fields
import django.db.models.deletion
from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('manga', '0045_alter_emotion_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='MangaPage',
            fields=[
                ('manga', annoying.fields.AutoOneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='site_page', serialize=False, to='manga.manga')),
            ],
        ),
    ]
