# Generated by Django 5.0.1 on 2024-03-20 15:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manga', '0045_alter_emotion_name'),
        ('manga_page', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mangapage',
            name='chapter_count',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='mangapage',
            name='chapter_likes_avg',
            field=models.DecimalField(decimal_places=7, default=None, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='mangapage',
            name='chapter_likes_sum',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='mangapage',
            name='comments_count',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='mangapage',
            name='comments_emotions_data',
            field=models.JSONField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='mangapage',
            name='comments_toxic_avg',
            field=models.DecimalField(decimal_places=7, default=None, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='mangapage',
            name='comments_toxic_count',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='mangapage',
            name='most_popular_chapter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='manga.chapter'),
        ),
        migrations.AddField(
            model_name='mangapage',
            name='most_popular_comment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='manga.comment'),
        ),
        migrations.AddField(
            model_name='mangapage',
            name='most_popular_page',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='manga.page'),
        ),
        migrations.AddField(
            model_name='mangapage',
            name='page_at_chapter_avg',
            field=models.DecimalField(decimal_places=7, default=None, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='mangapage',
            name='page_count',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='mangapage',
            name='update_at',
            field=models.DateField(auto_now=True),
        ),
    ]
