# Generated by Django 5.0.1 on 2024-03-20 15:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manga', '0045_alter_emotion_name'),
        ('manga_page', '0002_mangapage_chapter_count_mangapage_chapter_likes_avg_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mangapage',
            name='most_popular_chapter',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='manga.chapter'),
        ),
        migrations.AlterField(
            model_name='mangapage',
            name='most_popular_comment',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='manga.comment'),
        ),
        migrations.AlterField(
            model_name='mangapage',
            name='most_popular_page',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='manga.page'),
        ),
    ]
