# Generated by Django 5.0.1 on 2024-03-20 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manga_page', '0003_alter_mangapage_most_popular_chapter_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mangapage',
            name='chapter_likes_avg',
            field=models.DecimalField(decimal_places=8, default=None, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='mangapage',
            name='page_at_chapter_avg',
            field=models.DecimalField(decimal_places=5, default=None, max_digits=8, null=True),
        ),
    ]
