# Generated by Django 5.0.1 on 2024-03-20 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manga_page', '0007_alter_mangapage_least_popular_chapter_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mangapage',
            name='least_popular_chapter',
        ),
        migrations.RemoveField(
            model_name='mangapage',
            name='least_popular_comment',
        ),
        migrations.RemoveField(
            model_name='mangapage',
            name='least_popular_page',
        ),
        migrations.RemoveField(
            model_name='mangapage',
            name='most_popular_chapter',
        ),
        migrations.RemoveField(
            model_name='mangapage',
            name='most_popular_comment',
        ),
        migrations.RemoveField(
            model_name='mangapage',
            name='most_popular_page',
        ),
    ]
