# Generated by Django 5.0.3 on 2024-03-21 13:07

import annoying.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('manga', '0045_alter_emotion_name'),
        ('manga_page', '0009_delete_mangapage'),
    ]

    operations = [
        migrations.CreateModel(
            name='MangaPage',
            fields=[
                ('manga', annoying.fields.AutoOneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='site_page', serialize=False, to='manga.manga')),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('comments_count', models.IntegerField(default=None, null=True)),
                ('page_count', models.IntegerField(default=None, null=True)),
                ('chapter_count', models.IntegerField(default=None, null=True)),
                ('page_at_chapter_avg', models.DecimalField(decimal_places=5, default=None, max_digits=8, null=True)),
                ('chapter_likes_sum', models.IntegerField(default=None, null=True)),
                ('chapter_likes_avg', models.DecimalField(decimal_places=8, default=None, max_digits=12, null=True)),
                ('comments_toxic_count', models.IntegerField(default=None, null=True)),
                ('comments_toxic_avg', models.DecimalField(decimal_places=7, default=None, max_digits=8, null=True)),
                ('comments_emotions_data', models.JSONField(default=None, null=True)),
                ('least_popular_chapter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='least_popular_chapter', to='manga.chapter')),
                ('least_popular_comment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='least_popular_comment', to='manga.comment')),
                ('least_popular_page', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='least_popular_page', to='manga.page')),
                ('most_popular_chapter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='most_popular_chapter', to='manga.chapter')),
                ('most_popular_comment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='most_popular_comment', to='manga.comment')),
                ('most_popular_page', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='most_popular_page', to='manga.page')),
            ],
        ),
    ]
