# Generated by Django 5.0.3 on 2024-03-21 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manga_page', '0010_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mangapage',
            name='least_popular_chapter',
        ),
        migrations.RemoveField(
            model_name='mangapage',
            name='least_popular_comment',
        ),
        migrations.RemoveField(
            model_name='mangapage',
            name='least_popular_page',
        ),
        migrations.RemoveField(
            model_name='mangapage',
            name='most_popular_chapter',
        ),
        migrations.RemoveField(
            model_name='mangapage',
            name='most_popular_comment',
        ),
        migrations.RemoveField(
            model_name='mangapage',
            name='most_popular_page',
        ),
        migrations.AddField(
            model_name='mangapage',
            name='population_chapter',
            field=models.JSONField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='mangapage',
            name='population_page',
            field=models.JSONField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='mangapage',
            name='top_10_least_popular_comment',
            field=models.JSONField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='mangapage',
            name='top_10_most_popular_comment',
            field=models.JSONField(default=None, null=True),
        ),
    ]
