# Generated by Django 5.0.3 on 2024-03-21 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manga_page', '0011_remove_mangapage_least_popular_chapter_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mangapage',
            name='comments_toxic_count',
        ),
    ]
