# Generated by Django 5.0.3 on 2024-03-21 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manga_page', '0012_remove_mangapage_comments_toxic_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mangapage',
            name='chapter_likes_avg',
            field=models.DecimalField(decimal_places=4, default=None, max_digits=12, null=True),
        ),
    ]
