# Generated by Django 5.0.3 on 2024-03-21 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manga_page', '0013_alter_mangapage_chapter_likes_avg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mangapage',
            name='comments_toxic_avg',
            field=models.DecimalField(decimal_places=4, default=None, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='mangapage',
            name='page_at_chapter_avg',
            field=models.DecimalField(decimal_places=4, default=None, max_digits=8, null=True),
        ),
    ]
