# Generated by Django 5.0.3 on 2024-03-31 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manga_page', '0016_mangapage_population_chapter_compressed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mangapage',
            name='chapter_toxic_compressed',
            field=models.JSONField(default=None, null=True),
        ),
    ]
