# Generated by Django 5.0.3 on 2024-04-01 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manga_page', '0018_mangapage_chapters_at_days_of_the_week_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mangapage',
            name='chapters_at_24_hours',
            field=models.JSONField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='mangapage',
            name='comments_at_24_hours',
            field=models.JSONField(default=None, null=True),
        ),
    ]
