# Generated by Django 5.0.3 on 2024-04-02 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manga_page', '0019_mangapage_chapters_at_24_hours_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mangapage',
            name='page_of_chapter_toxic_compressed',
            field=models.JSONField(default=None, null=True),
        ),
    ]
