# Generated by Django 5.0.3 on 2024-04-05 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manga_page', '0021_mangapage_comments_toxic_avg_at_24_hour_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mangapage',
            name='is_ready',
            field=models.BooleanField(default=False),
        ),
    ]
