# Generated by Django 5.0.3 on 2024-04-05 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manga_page', '0022_mangapage_is_ready'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mangapage',
            name='is_ready',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
